# Generated by Django 4.1.3 on 2022-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('fruits_description', models.TextField()),
                ('is_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
